namespace TownOfUs
{
    public enum CustomRPC
    {
        SetJester = 100,
        SetCouple,
        SetMayor,
        SetSheriff,
        SetEngineer,
        SetSwapper,
        SetInvestigator,
        SetTimeLord,
        SetMedic,
        SetSeer,
        SetMorphling,
        SetCamouflager,
        SetExecutioner,
        SetTarget,
        SetSpy,
        SetSnitch,
        SetMiner,
        SetSwooper,
        SetJanitor,
        SetArsonist,
        SetAltruist,
        SetUndertaker,
        SetVigilante,
        SetGrenadier,
        SetVeteran,
        SetAmnesiac,
        SetJuggernaut,
        SetTracker,
        SetPoisoner,
        SetTransporter,
        SetMedium,
        SetSurvivor,
        SetGuardianAngel,
        SetGATarget,
        SetMystic,
        SetBlackmailer,
        SetPlaguebearer,
        SetWerewolf,
        SetTrapper,
        SetDetective,
        SetEscapist,

        SetTorch,
        SetDiseased,
        SetFlash,
        SetTiebreaker,
        SetGiant,
        SetButtonBarry,
        SetBait,
        SetSleuth,
        SetBlind,
        SetAssassin,
        SetRadar,
        SetDisperser,
        SetMultitasker,
        SetDoubleShot,
        SetUnderdog,

        SetPhantom,
        PhantomDied,
        CatchPhantom,

        SetHaunter,
        HaunterDied,
        CatchHaunter,

        SetTraitor,
        TraitorSpawn,

        SetCrewmate,
        SetImpostor,

        LoveWin,
        GlitchWin,
        JuggernautWin,
        ArsonistWin,
        PhantomWin,
        JesterLose,
        ExecutionerLose,
        AmnesiacLose,
        GlitchLose,
        JuggernautLose,
        ArsonistLose,
        NobodyWins,
        PhantomLose,
        SurvivorImpWin,
        SurvivorCrewWin,
        GAImpWin,
        GAImpLose,
        PlaguebearerWin,
        PlaguebearerLose,
        PestilenceWin,
        PestilenceLose,
        WerewolfWin,
        WerewolfLose,
        SurvivorOnlyWin,

        JanitorClean,
        FixLights,
        EngineerFix,
        SetExtraVotes,
        SetSwaps,
        Protect,
        AttemptSound,
        Rewind,
        RewindRevive,
        Morph,
        Mine,
        Swoop,
        Douse,
        Ignite,
        AltruistRevive,
        BarryButton,
        Drag,
        Drop,
        AssassinKill,
        VigilanteKill,
        HaunterFinished = 220,
        FlashGrenade,
        Alert,
        Remember,
        BaitReport,
        Transport,
        SetUntransportable,
        Mediate,
        Vest,
        GAProtect,
        Blackmail,
        Poison,
        Infect,
        TurnPestilence,
        Disperse,
        Escape,

        SetGlitch,
        BypassKill,
        SetMimic,
        RpcResetAnim,
        SetHacked,

        ExecutionerToJester,
        GAToSurv,

        Start,
        SyncCustomSettings,
        FixAnimation,
        SetPos,
        SetSettings,
        
        AddMayorVoteBank,
        RemoveAllBodies,
        CheckMurder,

        SubmergedFixOxygen
    }
}
