namespace TownOfUs
{
    public enum CustomRPC
    {
        SetRole = 100,
        SetModifier,
        SetCouple,
        SetAssassin,
        SetTarget,
        SetGATarget,
        SetDelayRoles,

        SetPhantom,
        CatchPhantom,

        SetHaunter,
        CatchHaunter,

        SetTraitor,

        LoveWin,
        GlitchWin,
        JuggernautWin,
        ArsonistWin,
        PhantomWin,
        JesterLose,
        ExecutionerLose,
        AmnesiacLose,
        GlitchLose,
        JuggernautLose,
        ArsonistLose,
        NobodyWins,
        PhantomLose,
        SurvivorImpWin,
        SurvivorCrewWin,
        GAImpWin,
        GAImpLose,
        PlaguebearerWin,
        PlaguebearerLose,
        PestilenceWin,
        PestilenceLose,
        WerewolfWin,
        WerewolfLose,
        SurvivorOnlyWin,

        JanitorClean,
        FixLights,
        EngineerFix,
        SetExtraVotes,
        SetSwaps,
        Protect,
        AttemptSound,
        Morph,
        Mine,
        Swoop,
        AltruistRevive,
        BarryButton,
        Drag,
        Drop,
        AssassinKill,
        VigilanteKill,
        HaunterFinished,
        FlashGrenade,
        Alert,
        Remember,
        BaitReport,
        Transport,
        SetUntransportable,
        Mediate,
        Vest,
        GAProtect,
        Blackmail,
        Infect,
        TurnPestilence,
        Disperse,
        Escape,
        Revive,
        Convert,
        ChameleonSwoop,
        Imitate,
        StartImitate,

        BypassKill,
        BypassMultiKill,
        SetMimic,
        RpcResetAnim,
        SetHacked,

        ExecutionerToJester,
        GAToSurv,

        Start,
        SyncCustomSettings,
        FixAnimation,
        SetPos,
        SetSettings,
        
        AddMayorVoteBank,
        RemoveAllBodies,
        CheckMurder,

        SubmergedFixOxygen
    }
}
