namespace TownOfUs
{
    public enum CustomRPC
    {
        SetJester = 100,
        SetCouple,
        SetMayor,
        SetSheriff,
        SetEngineer,
        SetSwapper,
        SetInvestigator,
        SetTimeLord,
        SetMedic,
        SetSeer,
        SetMorphling,
        SetCamouflager,
        SetExecutioner,
        SetTarget,
        SetSpy,
        SetSnitch,
        SetMiner,
        SetSwooper,
        SetJanitor,
        SetArsonist,
        SetAltruist,
        SetUndertaker,
        SetUnderdog,
        SetVigilante,
        SetGrenadier,
        SetVeteran,
        SetAmnesiac,
        SetJuggernaut,
        SetTracker,
        SetPoisoner,
        SetTransporter,

        SetTorch,
        SetDiseased,
        SetFlash,
        SetTiebreaker,
        SetDrunk,
        SetBigBoi,
        SetButtonBarry,
        SetBait,
        SetSleuth,
        SetAssassin,

        SetPhantom,
        PhantomDied,
        CatchPhantom,

        SetHaunter,
        HaunterDied,
        CatchHaunter,

        SetTraitor,
        TraitorSpawn,

        SetCrewmate,
        SetImpostor,


        LoveWin,
        GlitchWin,
        JuggernautWin,
        ArsonistWin,
        PhantomWin,
        JesterLose,
        ExecutionerLose,
        AmnesiacLose,
        GlitchLose,
        JuggernautLose,
        ArsonistLose,
        NobodyWins,
        PhantomLose,

        JanitorClean,
        FixLights,
        EngineerFix,
        SetExtraVotes,
        SetSwaps,
        Protect,
        AttemptSound,
        Investigate,
        Rewind,
        RewindRevive,
        Morph,
        Camouflage,
        Mine,
        Swoop,
        Douse,
        Ignite,
        AltruistRevive,
        BarryButton,
        Drag,
        Drop,
        AssassinKill,
        VigilanteKill,
        HaunterFinished,
        FlashGrenade,
        Alert,
        Remember,
        BaitReport,
        Transport,

        SetGlitch,
        BypassKill,
        SetMimic,
        RpcResetAnim,
        SetHacked,

        ExecutionerToJester,


        Start,
        SyncCustomSettings,
        FixAnimation,
        
        AddMayorVoteBank,
        RemoveAllBodies
    }
}
